/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Tashfiq
 */
public class DoctorAccount extends javax.swing.JFrame {

    /**
     * Creates new form DoctorAccount
     */

    
    String docName,docSpec,docContact,docPic,userEmail,userId;
    ConnectMSSQL cnObj;
    
    public DoctorAccount(String _doctorEmail) {
        initComponents();
        
        DoctorPictureLabel.setBackground(new Color(0,0,0,0));
        editDocButton.setBackground(new Color(0,0,0,0));
        SignOutDoctorButton.setBackground(new Color(0,0,0,0));

        userEmail = _doctorEmail;
        
        
        
        try {
            //get all doc data and fill up the account
            cnObj = new ConnectMSSQL();
            cnObj.getDocData(userEmail);
            cnObj.resultSet.next();
            
            docName=cnObj.resultSet.getString("DoctorName");
            docSpec=cnObj.resultSet.getString("Speciality");
            docContact = cnObj.resultSet.getString("DoctorContactNumber");
            docPic =cnObj.resultSet.getString("DoctorPicture");
            userId= cnObj.resultSet.getString("DoctorId");
            
            doctorName.setText(docName);
            doctorSpec.setText(docSpec);
            doctorId.setText(userId);
            doctorEmail.setText(userEmail);
            doctorContactNumber.setText(docContact);
            
            //get all presription data and fill up the prescription table located below 
            cnObj = new ConnectMSSQL();
            cnObj.getDocPrescriptionData(userId) ;
            String[] column_name = cnObj.q_label.toArray(new String[cnObj.q_label.size()]);
            String[][] table_data = cnObj.q_data.stream().map(u -> u.toArray(new String[0])).toArray(String[][]::new);
            DefaultTableModel model = (DefaultTableModel)docDetailTable.getModel();
            model.setDataVector(table_data, column_name);
            
        } catch (SQLException ex) {
            Logger.getLogger(DoctorAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DoctorPictureLabel = new javax.swing.JLabel();
        doctorName = new javax.swing.JLabel();
        SpecialtyLabel = new javax.swing.JLabel();
        doctorSpec = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doctorId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        doctorEmail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        doctorContactNumber = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        editDocButton = new javax.swing.JButton();
        SignOutDoctorButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        docDetailTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(228, 255, 222));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DOCTOR PROFILE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 4, 200, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        DoctorPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/DocAccount.png"))); // NOI18N
        jPanel1.add(DoctorPictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 100));

        doctorName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        doctorName.setText("Hasanath Jamy");
        jPanel1.add(doctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 260, 30));

        SpecialtyLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        SpecialtyLabel.setText("Speciality:");
        jPanel1.add(SpecialtyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 80, 30));

        doctorSpec.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        doctorSpec.setText("no value");
        jPanel1.add(doctorSpec, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 120, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Doctor ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 140, 30));

        doctorId.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        doctorId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctorId.setText("no value");
        jPanel1.add(doctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 260, 130, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 3, 60));

        doctorEmail.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        doctorEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctorEmail.setText("no value");
        jPanel1.add(doctorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 230, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email Address:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 170, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contact Number:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 130, 30));

        doctorContactNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        doctorContactNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctorContactNumber.setText("no value");
        jPanel1.add(doctorContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 260, 140, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        jSeparator2.setOpaque(true);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 3, 60));

        editDocButton.setForeground(new java.awt.Color(255, 255, 255));
        editDocButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/editbotton2.png"))); // NOI18N
        editDocButton.setBorder(null);
        editDocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDocButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editDocButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 90, 30));

        SignOutDoctorButton.setForeground(new java.awt.Color(255, 255, 255));
        SignOutDoctorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/exit.png"))); // NOI18N
        SignOutDoctorButton.setBorder(null);
        SignOutDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutDoctorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SignOutDoctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 40, 40));

        docDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        docDetailTable.setRowHeight(25);
        docDetailTable.setSelectionBackground(new java.awt.Color(150, 252, 88));
        docDetailTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        docDetailTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                docDetailTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(docDetailTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 900, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/b5_1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 900, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusLost

    private void SignOutDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutDoctorButtonActionPerformed
        // TODO add your handling code here:
        Menu.main(null);
        this.dispose();
    }//GEN-LAST:event_SignOutDoctorButtonActionPerformed

    private void docDetailTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_docDetailTableMouseClicked
        // TODO add your handling code here:
        int clickedRow = docDetailTable.getSelectedRow();
        //System.out.println(clickedRow);
        String selectedPrescriptionId = cnObj.docPrescriptionIdList.get(clickedRow);
        //System.out.println(selectedPrescriptionId);
        String accType = "doc";
        PrescribedPrescription.createForm(selectedPrescriptionId,accType,userEmail);
        this.dispose();
    }//GEN-LAST:event_docDetailTableMouseClicked

    private void editDocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDocButtonActionPerformed
        // TODO add your handling code here:
        DoctorUpdate.createForm(userId,userEmail);
        this.dispose();
        
    }//GEN-LAST:event_editDocButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void createForm(String _doctorEmail)
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorAccount(_doctorEmail).setVisible(true);
            }
        });
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorAccount(_doctorEmail).setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DoctorPictureLabel;
    private javax.swing.JButton SignOutDoctorButton;
    private javax.swing.JLabel SpecialtyLabel;
    private javax.swing.JTable docDetailTable;
    private javax.swing.JLabel doctorContactNumber;
    private javax.swing.JLabel doctorEmail;
    private javax.swing.JLabel doctorId;
    private javax.swing.JLabel doctorName;
    private javax.swing.JLabel doctorSpec;
    private javax.swing.JButton editDocButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
