/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
/**
 *
 * @author Tashfiq
 */
public class DoctorSignUp extends javax.swing.JFrame {

    /**
     * Creates new form DoctorSignUp
     */
    public DoctorSignUp() {
        initComponents();
        
        DoctorNameTextField.setBackground(new Color(0,0,0,0));
        DoctorEmailTextField.setBackground(new Color(0,0,0,0));
        DoctorContactNumberTextField.setBackground(new Color(0,0,0,0));
        DoctorSpecialityTextField.setBackground(new Color(0,0,0,0));
        DoctorPasswordField.setBackground(new Color(0,0,0,0));
        DoctorConfirmPasswordField.setBackground(new Color(0,0,0,0));
        DoctorSignUpButton.setBackground(new Color(0,0,0,0)); 
        DoctorSignUpBackButton.setBackground(new Color(0,0,0,0)); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DoctorNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DoctorEmailTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        DoctorContactNumberTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        DoctorSpecialityTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DoctorPasswordField = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        DoctorConfirmPasswordField = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DoctorSignUpButton = new javax.swing.JButton();
        DoctorSignUpBackButton = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("R E G I S T E R");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 140, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 153, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("IT'S COMPLETELY FREE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 240, 30));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(38, 0, 0));
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 190, 30));

        DoctorNameTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        DoctorNameTextField.setForeground(new java.awt.Color(0, 51, 51));
        DoctorNameTextField.setText("Enter Full Name");
        DoctorNameTextField.setBorder(null);
        DoctorNameTextField.setOpaque(false);
        DoctorNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoctorNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DoctorNameTextFieldFocusLost(evt);
            }
        });
        DoctorNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 230, 30));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(38, 0, 0));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 30));

        DoctorEmailTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        DoctorEmailTextField.setForeground(new java.awt.Color(0, 51, 51));
        DoctorEmailTextField.setText("Enter Email");
        DoctorEmailTextField.setBorder(null);
        DoctorEmailTextField.setOpaque(false);
        DoctorEmailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoctorEmailTextFieldFocusGained(evt);
            }
        });
        DoctorEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorEmailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 230, 30));

        jLabel12.setBackground(new java.awt.Color(153, 153, 153));
        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(38, 0, 0));
        jLabel12.setText("Contact Number");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 190, 30));

        DoctorContactNumberTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        DoctorContactNumberTextField.setForeground(new java.awt.Color(0, 51, 51));
        DoctorContactNumberTextField.setText("Enter Contact Number");
        DoctorContactNumberTextField.setBorder(null);
        DoctorContactNumberTextField.setOpaque(false);
        DoctorContactNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoctorContactNumberTextFieldFocusGained(evt);
            }
        });
        DoctorContactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorContactNumberTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorContactNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 30));

        jLabel13.setBackground(new java.awt.Color(153, 153, 153));
        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(38, 0, 0));
        jLabel13.setText("Speciality");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 190, 30));

        DoctorSpecialityTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        DoctorSpecialityTextField.setForeground(new java.awt.Color(0, 51, 51));
        DoctorSpecialityTextField.setText("Enter Speciality");
        DoctorSpecialityTextField.setBorder(null);
        DoctorSpecialityTextField.setOpaque(false);
        DoctorSpecialityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoctorSpecialityTextFieldFocusGained(evt);
            }
        });
        DoctorSpecialityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorSpecialityTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorSpecialityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 30));

        jLabel5.setBackground(new java.awt.Color(153, 153, 153));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 0, 0));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 190, 30));

        DoctorPasswordField.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        DoctorPasswordField.setForeground(new java.awt.Color(51, 51, 51));
        DoctorPasswordField.setText("EnterPassword");
        DoctorPasswordField.setBorder(null);
        DoctorPasswordField.setOpaque(false);
        DoctorPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoctorPasswordFieldFocusGained(evt);
            }
        });
        DoctorPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 230, 30));

        jLabel15.setBackground(new java.awt.Color(153, 153, 153));
        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(38, 0, 0));
        jLabel15.setText("Confirm Password");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 190, 30));

        DoctorConfirmPasswordField.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        DoctorConfirmPasswordField.setForeground(new java.awt.Color(51, 51, 51));
        DoctorConfirmPasswordField.setText("EnterPassword");
        DoctorConfirmPasswordField.setBorder(null);
        DoctorConfirmPasswordField.setOpaque(false);
        DoctorConfirmPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoctorConfirmPasswordFieldFocusGained(evt);
            }
        });
        DoctorConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorConfirmPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 230, 30));

        jCheckBox1.setBackground(new java.awt.Color(102, 102, 102));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("<html>\n<body>\n<u>Terms And Conditions</u>\n</body>\n</html>\n\n");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 200, 40));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel8.setText("Agree");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 200, 40));

        DoctorSignUpButton.setBackground(new java.awt.Color(36, 33, 44));
        DoctorSignUpButton.setForeground(new java.awt.Color(36, 33, 44));
        DoctorSignUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/Sign up.png"))); // NOI18N
        DoctorSignUpButton.setBorder(null);
        DoctorSignUpButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoctorSignUpButtonFocusGained(evt);
            }
        });
        DoctorSignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorSignUpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorSignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 100, 40));

        DoctorSignUpBackButton.setBackground(new java.awt.Color(36, 33, 44));
        DoctorSignUpBackButton.setForeground(new java.awt.Color(36, 33, 44));
        DoctorSignUpBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/back2.png"))); // NOI18N
        DoctorSignUpBackButton.setBorder(null);
        DoctorSignUpBackButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DoctorSignUpBackButtonFocusGained(evt);
            }
        });
        DoctorSignUpBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorSignUpBackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorSignUpBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 100, 40));

        jSeparator6.setBackground(new java.awt.Color(51, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(51, 0, 0));
        jSeparator6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 260, 2));

        jSeparator5.setBackground(new java.awt.Color(51, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(51, 0, 0));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 260, 2));

        jSeparator4.setBackground(new java.awt.Color(51, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(51, 0, 0));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 260, 2));

        jSeparator3.setBackground(new java.awt.Color(51, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(51, 0, 0));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 260, 2));

        jSeparator2.setBackground(new java.awt.Color(51, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(51, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 260, 2));

        jSeparator1.setBackground(new java.awt.Color(51, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0)));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 260, 2));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/b4.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoctorNameTextFieldFocusGained
        // TODO add your handling code here:
        DoctorNameTextField.setText("");
    }//GEN-LAST:event_DoctorNameTextFieldFocusGained

    private void DoctorNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoctorNameTextFieldFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_DoctorNameTextFieldFocusLost

    private void DoctorNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorNameTextFieldActionPerformed

    private void DoctorEmailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoctorEmailTextFieldFocusGained
        // TODO add your handling code here:
        DoctorEmailTextField.setText("");
    }//GEN-LAST:event_DoctorEmailTextFieldFocusGained

    private void DoctorEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorEmailTextFieldActionPerformed

    private void DoctorContactNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoctorContactNumberTextFieldFocusGained
        // TODO add your handling code here:
        DoctorContactNumberTextField.setText("");
    }//GEN-LAST:event_DoctorContactNumberTextFieldFocusGained

    private void DoctorContactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorContactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorContactNumberTextFieldActionPerformed

    private void DoctorSpecialityTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoctorSpecialityTextFieldFocusGained
        // TODO add your handling code here:
        DoctorSpecialityTextField.setText("");
    }//GEN-LAST:event_DoctorSpecialityTextFieldFocusGained

    private void DoctorSpecialityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorSpecialityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorSpecialityTextFieldActionPerformed

    private void DoctorPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoctorPasswordFieldFocusGained
        // TODO add your handling code here:
        DoctorPasswordField.setText("");
    }//GEN-LAST:event_DoctorPasswordFieldFocusGained

    private void DoctorPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorPasswordFieldActionPerformed

    private void DoctorConfirmPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoctorConfirmPasswordFieldFocusGained
        // TODO add your handling code here:
        DoctorConfirmPasswordField.setText("");
    }//GEN-LAST:event_DoctorConfirmPasswordFieldFocusGained

    private void DoctorConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorConfirmPasswordFieldActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void DoctorSignUpButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoctorSignUpButtonFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_DoctorSignUpButtonFocusGained

    private void DoctorSignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorSignUpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorSignUpButtonActionPerformed

    private void DoctorSignUpBackButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DoctorSignUpBackButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorSignUpBackButtonFocusGained

    private void DoctorSignUpBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorSignUpBackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorSignUpBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField DoctorConfirmPasswordField;
    private javax.swing.JTextField DoctorContactNumberTextField;
    private javax.swing.JTextField DoctorEmailTextField;
    private javax.swing.JTextField DoctorNameTextField;
    private javax.swing.JPasswordField DoctorPasswordField;
    private javax.swing.JButton DoctorSignUpBackButton;
    private javax.swing.JButton DoctorSignUpButton;
    private javax.swing.JTextField DoctorSpecialityTextField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
