
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tashfiq
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        SignUpButton.setBackground(new Color(0, 0, 0, 0));
        SignInButton.setBackground(new Color(0, 0, 0, 0));
        radSelectedState.setText("Please Select Your Account Type");
        docRadButton.setSelected(false);
        patRadButton.setSelected(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountChoosebuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        docRadButton = new javax.swing.JRadioButton();
        patRadButton = new javax.swing.JRadioButton();
        emailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        SignInButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        radSelectedState = new javax.swing.JLabel();
        Please = new javax.swing.JLabel();
        errorField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient and Prescription Management System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHOOSE ACCOUNT TYPE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, 30));

        AccountChoosebuttonGroup.add(docRadButton);
        docRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/Doc.png"))); // NOI18N
        docRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docRadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(docRadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, 150));

        AccountChoosebuttonGroup.add(patRadButton);
        patRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/patient.png"))); // NOI18N
        patRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patRadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(patRadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 150, 150));

        emailField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(102, 102, 102));
        emailField.setText("example123@gmail.com");
        emailField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));
        emailField.setOpaque(false);
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
        });
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 350, 40));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 190, 40));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 190, 40));

        passwordField.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        passwordField.setForeground(new java.awt.Color(153, 153, 153));
        passwordField.setText("EnterPassword");
        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true));
        passwordField.setOpaque(false);
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 350, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("No account?");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 70, 30));

        SignInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/signin.png"))); // NOI18N
        SignInButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true));
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SignInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 70, 30));

        SignUpButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(0, 102, 102));
        SignUpButton.setText("SignUp");
        SignUpButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SignUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 80, 30));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        radSelectedState.setBackground(new java.awt.Color(255, 255, 255));
        radSelectedState.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radSelectedState.setForeground(new java.awt.Color(102, 102, 102));
        radSelectedState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        radSelectedState.setText("Hello doctor");
        jPanel1.add(radSelectedState, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 280, 30));

        Please.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Please.setForeground(new java.awt.Color(102, 102, 102));
        Please.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Please.setText("Please Fill Out the Form to Get Started");
        jPanel1.add(Please, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 280, 30));

        errorField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        errorField.setForeground(new java.awt.Color(200, 1, 1));
        errorField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorField.setText("error code");
        jPanel1.add(errorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 350, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
        emailField.setText("");
    }//GEN-LAST:event_emailFieldFocusGained

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        // TODO add your handling code here:
        passwordField.setText("");
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
        if (!docRadButton.isSelected() && !patRadButton.isSelected()) 
            errorField.setText("Please Select an Account Type!!!");
        else 
        {
            if (patRadButton.isSelected()) 
                SignUpPatient.main(null);
            else SignUpDoctor.main(null);
            this.dispose();
        }
        
         
        
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void docRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docRadButtonActionPerformed
        // TODO add your handling code here:
        radSelectedState.setText("Welcome Doctor!!");
    }//GEN-LAST:event_docRadButtonActionPerformed

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        // TODO add your handling code here:
        String email, password,tempEmail,tempPass;
        email = emailField.getText().trim().toLowerCase();
        password = new String(passwordField.getPassword());
        if (!docRadButton.isSelected() && !patRadButton.isSelected()) {
            errorField.setText("Please Select an Account Type!!!");
        } else if (email.isEmpty()) {
            errorField.setText("Invalid Email or Password!!!");
        } else {
            
            if (patRadButton.isSelected()) 
            {
                ConnectMSSQL cnObj = new ConnectMSSQL();
                cnObj.patientAuth();
                try {
                    while (cnObj.resultSet.next()) 
                    {
                        tempEmail = cnObj.resultSet.getString("patientEmail");
                        tempPass = cnObj.resultSet.getString("patientPassword");
                        if (email.equals(tempEmail) && password.equals(tempPass)) 
                        {
                            PatientAccount.createForm(tempEmail);
                            this.dispose();
                            //MinhajulIslam@gmail.com
                            //islam
                            break;
                        }
                    }               
                    errorField.setText("Invalid Email or Password!!!");
                } catch (SQLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else if(docRadButton.isSelected())
            {
                ConnectMSSQL cnObj = new ConnectMSSQL();
                cnObj.doctorAuth();
                try {
                    while(cnObj.resultSet.next())
                    {
                        tempEmail = cnObj.resultSet.getString("doctorEmail");
                        tempPass = cnObj.resultSet.getString("doctorPassword");
                        if (email.equals(tempEmail) && password.equals(tempPass)) 
                        {
                            DoctorAccount.createForm(tempEmail);
                            this.dispose();
                            //AmitHasan@gmail.com
                            //hasan
                            break;
                        }
                    }
                    System.out.println("doc");
                    errorField.setText("Invalid Email or Password!!!");
                } catch (SQLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }


    }//GEN-LAST:event_SignInButtonActionPerformed

    private void patRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patRadButtonActionPerformed
        // TODO add your handling code here:
        radSelectedState.setText("Welcome Patient!!");
    }//GEN-LAST:event_patRadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AccountChoosebuttonGroup;
    private javax.swing.JLabel Please;
    private javax.swing.JButton SignInButton;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JRadioButton docRadButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel errorField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JRadioButton patRadButton;
    private javax.swing.JLabel radSelectedState;
    // End of variables declaration//GEN-END:variables
}
