/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Tashfiq
 */
public class PatientAccount extends javax.swing.JFrame {

    /**
     * Creates new form PatientAccount
     */

    String patName,patEmail,patContact,patDob,patPic,userId,userEmail;
    ConnectMSSQL cnObj;

    public PatientAccount(String _patientEmail) {

        initComponents();
        
        PatientPictureLabel.setBackground(new Color(0, 0, 0, 0));
        editPatButton.setBackground(new Color(0, 0, 0, 0));
        signOutPatButton.setBackground(new Color(0, 0, 0, 0));
        
        userEmail =_patientEmail;
        
        try {
            //get all pat data and fill up the account 
            cnObj = new ConnectMSSQL();
            cnObj.getPatData(userEmail);
            cnObj.resultSet.next();
            userId=cnObj.resultSet.getString("PatientId");
            patName=cnObj.resultSet.getString("PatientName");
            patEmail=cnObj.resultSet.getString("patientEmail");
            patContact=cnObj.resultSet.getString("patientContactNumber");
            patDob=cnObj.resultSet.getString("DateOfBirth");
            patPic = cnObj.resultSet.getString("PatientPicture");

            patientName.setText(patName);
            patientContactNumber.setText(patContact);
            patientId.setText(userId);
            patientEmail.setText(patEmail);
            String tempDate = patDob;
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd").withLocale(Locale.US);
            LocalDate date = LocalDate.parse(tempDate, formatter);
            int age = Period.between(date,LocalDate.now()).getYears();
            patientAge.setText(String.valueOf(age) );
            
            //get all presription data and fill up the prescription table located below 
            cnObj = new ConnectMSSQL();
            cnObj.getPatPrescriptionData(userId) ;
            
            String[] column_name = cnObj.q_label.toArray(new String[cnObj.q_label.size()]);
            String[][] table_data = cnObj.q_data.stream().map(u -> u.toArray(new String[0])).toArray(String[][]::new);
            DefaultTableModel model = (DefaultTableModel)patDetailTable.getModel();
            model.setDataVector(table_data, column_name);
            
        } catch (SQLException ex) {
        }

    }
    public static void createForm(String _patientEmail)
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientAccount(_patientEmail).setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PatientPictureLabel = new javax.swing.JLabel();
        patientName = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        patientAge = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        patientEmail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        patientContactNumber = new javax.swing.JLabel();
        editPatButton = new javax.swing.JButton();
        signOutPatButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patDetailTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PATIENT PROFILE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 4, 200, 40));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        PatientPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/patientAccount.png"))); // NOI18N
        jPanel1.add(PatientPictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 100, 100));

        patientName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        patientName.setForeground(new java.awt.Color(255, 255, 255));
        patientName.setText("Hasanath Jamy");
        jPanel1.add(patientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 260, 30));

        AgeLabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        AgeLabel.setForeground(new java.awt.Color(255, 255, 255));
        AgeLabel.setText("Age:");
        jPanel1.add(AgeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 40, 30));

        patientAge.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        patientAge.setForeground(new java.awt.Color(255, 255, 255));
        patientAge.setText("2");
        jPanel1.add(patientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 120, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Patient ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 140, 30));

        patientId.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        patientId.setForeground(new java.awt.Color(255, 255, 255));
        patientId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientId.setText("170104039");
        jPanel1.add(patientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 250, 130, 30));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jSeparator1.setOpaque(true);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 3, 60));

        patientEmail.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        patientEmail.setForeground(new java.awt.Color(255, 255, 255));
        patientEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientEmail.setText("jamy.hasanath03@gmail.com");
        jPanel1.add(patientEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 230, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email Address:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 170, 30));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jSeparator2.setOpaque(true);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 3, 60));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contact Number:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 130, 30));

        patientContactNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        patientContactNumber.setForeground(new java.awt.Color(255, 255, 255));
        patientContactNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientContactNumber.setText("01688834948");
        jPanel1.add(patientContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 250, 140, 30));

        editPatButton.setForeground(new java.awt.Color(255, 255, 255));
        editPatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/editbotton2.png"))); // NOI18N
        editPatButton.setBorder(null);
        editPatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPatButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editPatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 90, 30));

        signOutPatButton.setForeground(new java.awt.Color(255, 255, 255));
        signOutPatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/exit.png"))); // NOI18N
        signOutPatButton.setBorder(null);
        signOutPatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutPatButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signOutPatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 40, 40));

        patDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        patDetailTable.setRowHeight(25);
        patDetailTable.setSelectionBackground(new java.awt.Color(119, 245, 255));
        patDetailTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        patDetailTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patDetailTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(patDetailTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 900, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/b3_1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 900, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signOutPatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutPatButtonActionPerformed
        // TODO add your handling code here:
        Menu.main(null);
        this.dispose();
    }//GEN-LAST:event_signOutPatButtonActionPerformed

    private void editPatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPatButtonActionPerformed
        // TODO add your handling code here:
        PatientUpdate.createForm(userId,userEmail);
        this.dispose();
    }//GEN-LAST:event_editPatButtonActionPerformed

    private void patDetailTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patDetailTableMouseClicked
        // TODO add your handling code here:
        int clickedRow = patDetailTable.getSelectedRow();
        String selectedPrescriptionId = cnObj.patPrescriptionIdList.get(clickedRow);
        String accType = "pat";
        
        PrescribedPrescription.createForm(selectedPrescriptionId,accType,userEmail);
        this.dispose();
        //System.out.println(selectedPrescriptionId);
    }//GEN-LAST:event_patDetailTableMouseClicked

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientAccount(_patientEmail).setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JLabel PatientPictureLabel;
    private javax.swing.JButton editPatButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable patDetailTable;
    private javax.swing.JLabel patientAge;
    private javax.swing.JLabel patientContactNumber;
    private javax.swing.JLabel patientEmail;
    private javax.swing.JLabel patientId;
    private javax.swing.JLabel patientName;
    private javax.swing.JButton signOutPatButton;
    // End of variables declaration//GEN-END:variables
}
