/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tashfiq
 */
public class PatientUpdate extends javax.swing.JFrame {

    /**
     * Creates new form PatientUpdate
     */
    String userId,userEmail;

    public PatientUpdate(String _patientId, String _patientEmail) {
        initComponents();

        nameField.setBackground(new Color(0, 0, 0, 0));
        passField.setBackground(new Color(0, 0, 0, 0));
        contactNumberField.setBackground(new Color(0, 0, 0, 0));
        emailField.setBackground(new Color(0, 0, 0, 0));
        confirmPassField.setBackground(new Color(0, 0, 0, 0));
        PatientUpdateButton.setBackground(new Color(0, 0, 0, 0));
        PatientUpdateBackButton.setBackground(new Color(0, 0, 0, 0));
        /*DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd").withLocale(Locale.US);
        LocalDate localDate = LocalDate.parse("1960-01-15", formatter);
        JDateChooser.setDate( Date.valueOf(localDate));*/

        userId = _patientId;
        userEmail = _patientEmail;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        contactNumberField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        confirmPassField = new javax.swing.JPasswordField();
        PatientUpdateButton = new javax.swing.JButton();
        PatientUpdateBackButton = new javax.swing.JButton();
        passErrorText = new javax.swing.JLabel();
        contactErrorText = new javax.swing.JLabel();
        emailErrorText = new javax.swing.JLabel();
        nameErrorText = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("U P D A T E       I N F O R M A T I O N");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 230, 30));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 190, 30));

        nameField.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        nameField.setForeground(new java.awt.Color(153, 153, 153));
        nameField.setText("Enter Full Name");
        nameField.setBorder(null);
        nameField.setOpaque(false);
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 230, 30));

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 190, 30));

        emailField.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        emailField.setForeground(new java.awt.Color(153, 153, 153));
        emailField.setText("Enter Email");
        emailField.setBorder(null);
        emailField.setOpaque(false);
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 230, 30));

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contact Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 190, 30));

        contactNumberField.setFont(new java.awt.Font("Berlin Sans FB", 0, 10)); // NOI18N
        contactNumberField.setForeground(new java.awt.Color(153, 153, 153));
        contactNumberField.setText("Enter Contact Number");
        contactNumberField.setBorder(null);
        contactNumberField.setOpaque(false);
        contactNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactNumberFieldFocusGained(evt);
            }
        });
        contactNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberFieldActionPerformed(evt);
            }
        });
        jPanel1.add(contactNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 230, 30));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 190, 20));

        passField.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        passField.setForeground(new java.awt.Color(153, 153, 153));
        passField.setText("EnterPassword");
        passField.setBorder(null);
        passField.setOpaque(false);
        passField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFieldFocusGained(evt);
            }
        });
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        jPanel1.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 230, 30));

        jLabel14.setBackground(new java.awt.Color(153, 153, 153));
        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Confirm Password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 190, 30));

        confirmPassField.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        confirmPassField.setForeground(new java.awt.Color(153, 153, 153));
        confirmPassField.setText("EnterPassword");
        confirmPassField.setBorder(null);
        confirmPassField.setOpaque(false);
        confirmPassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPassFieldFocusGained(evt);
            }
        });
        confirmPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassFieldActionPerformed(evt);
            }
        });
        jPanel1.add(confirmPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 230, 30));

        PatientUpdateButton.setBackground(new java.awt.Color(36, 33, 44));
        PatientUpdateButton.setForeground(new java.awt.Color(36, 33, 44));
        PatientUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/update.png"))); // NOI18N
        PatientUpdateButton.setBorder(null);
        PatientUpdateButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PatientUpdateButtonFocusGained(evt);
            }
        });
        PatientUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientUpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PatientUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 90, 30));

        PatientUpdateBackButton.setBackground(new java.awt.Color(36, 33, 44));
        PatientUpdateBackButton.setForeground(new java.awt.Color(36, 33, 44));
        PatientUpdateBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/back2.png"))); // NOI18N
        PatientUpdateBackButton.setBorder(null);
        PatientUpdateBackButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PatientUpdateBackButtonFocusGained(evt);
            }
        });
        PatientUpdateBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientUpdateBackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PatientUpdateBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 475, 100, 40));

        passErrorText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passErrorText.setForeground(new java.awt.Color(255, 255, 255));
        passErrorText.setText("pass");
        jPanel1.add(passErrorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 260, 20));

        contactErrorText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contactErrorText.setForeground(new java.awt.Color(255, 255, 255));
        contactErrorText.setText("conl7");
        jPanel1.add(contactErrorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 260, 20));

        emailErrorText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailErrorText.setForeground(new java.awt.Color(255, 255, 255));
        emailErrorText.setText("mail");
        jPanel1.add(emailErrorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 260, 20));

        nameErrorText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameErrorText.setForeground(new java.awt.Color(255, 255, 255));
        nameErrorText.setText("name");
        jPanel1.add(nameErrorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 260, 20));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator6.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 260, 10));

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 260, 10));

        jSeparator3.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 260, 5));

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 260, 10));

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 260, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/b1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 540));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/b2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 350, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        // TODO add your handling code here:
        nameField.setText("");
    }//GEN-LAST:event_nameFieldFocusGained

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
        emailField.setText("");
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void contactNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactNumberFieldFocusGained
        // TODO add your handling code here:
        contactNumberField.setText("");
    }//GEN-LAST:event_contactNumberFieldFocusGained

    private void contactNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberFieldActionPerformed

    private void passFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFieldFocusGained
        // TODO add your handling code here:
        passField.setText("");
    }//GEN-LAST:event_passFieldFocusGained

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void confirmPassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPassFieldFocusGained
        // TODO add your handling code here:
        confirmPassField.setText("");
    }//GEN-LAST:event_confirmPassFieldFocusGained

    private void confirmPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassFieldActionPerformed

    private void PatientUpdateButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PatientUpdateButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientUpdateButtonFocusGained

    private void PatientUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientUpdateButtonActionPerformed
        // TODO add your handling code here      
        String name, email, contactNumber, pass;
        if (!nameField.getText().trim().isEmpty() && !nameField.getText().trim().equals("Enter Full Name")) {
            name = nameField.getText().trim();
            try {

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection(
                        "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                Statement statement = connection.createStatement();

                statement.executeUpdate("Update PATIENT set patientName=\'" + name + "\' where patientId=" + userId);
                nameErrorText.setForeground(new Color(0, 255, 0, 255));
                nameErrorText.setText("Updated Name Successfully!!!");
            } catch (Exception ex) {
                Logger.getLogger(PatientUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (!String.valueOf(passField.getPassword()).isEmpty() && !String.valueOf(passField.getPassword()).equals("EnterPassword")) 
        {
            if (String.valueOf(passField.getPassword()).equals(String.valueOf(confirmPassField.getPassword()))) {
                pass = String.valueOf(passField.getPassword());
                try {

                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection connection = DriverManager.getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                    Statement statement = connection.createStatement();

                    statement.executeUpdate("Update PATIENT set patientPassword=\'" + pass + "\' where patientId=" + userId);
                    
                    passErrorText.setForeground(new Color(0, 255, 0, 255));
                    passErrorText.setText("Updated Password Successfully!!!");
                } catch (Exception ex) {
                    Logger.getLogger(PatientUpdate.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else 
            {
                passErrorText.setForeground(new Color(255, 0, 0, 255));
                passErrorText.setText("Password Update Not Successful!!!");
            }
        }

        if (!contactNumberField.getText().trim().isEmpty() && !contactNumberField.getText().trim().equals("Enter Contact Number")) {
            contactNumber = contactNumberField.getText().trim();
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection(
                        "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                Statement statement = connection.createStatement();
                ResultSet tempSet = statement.executeQuery("select * from PATIENT where patientContactNumber=\'" + contactNumber+"\'");
                
                while(tempSet.next()){};

                if (tempSet.getRow() == 0) // if value is 0 then update
                {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection connection2 = DriverManager.getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                    Statement statement2 = connection2.createStatement();
                    
                    statement2.executeUpdate("Update PATIENT set patientContactNumber=\'" + contactNumber + "\' where patientId=" + userId);
                    contactErrorText.setForeground(new Color(0, 255, 0, 255));
                    contactErrorText.setText("Updated Contact Number Successfully!!!");
                } else {
                    contactErrorText.setForeground(new Color(255, 0, 0, 255));
                    contactErrorText.setText("This Contact Number Already Exists!!!");
                }

            } catch (Exception ex) {
                Logger.getLogger(PatientUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //('Minhajul Islam', 'minhajulislam@gmail.com', 'islam', 'Male', '1996-01-01', '01712345671' ),
        if (!emailField.getText().trim().toLowerCase().isEmpty() && !emailField.getText().trim().equals("Enter Email")) {
            email = emailField.getText().trim().toLowerCase();
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection(
                        "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                Statement statement = connection.createStatement();
                ResultSet tempSet = statement.executeQuery("select * from PATIENT where patientEmail=\'" + email + "\'");
                
                while(tempSet.next()){};
                
                if (tempSet.getRow() == 0) // if value is 0 then update
                {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection connection2 = DriverManager.getConnection(
                            "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "123456");
                    Statement statement2 = connection2.createStatement();

                    statement2.executeUpdate("Update PATIENT set patientEmail=\'" + email + "\' where patientId=" + userId);
                    userEmail=email;
                    
                    emailErrorText.setForeground(new Color(0, 255, 0, 255));
                    emailErrorText.setText("Updated Email Successfully!!!");
                }
                else 
                {
                    emailErrorText.setForeground(new Color(255, 0, 0, 255));
                    emailErrorText.setText("This Email Already Exists!!!");
                }
            } catch (Exception ex) {
                Logger.getLogger(PatientUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_PatientUpdateButtonActionPerformed

    private void PatientUpdateBackButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PatientUpdateBackButtonFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientUpdateBackButtonFocusGained

    private void PatientUpdateBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientUpdateBackButtonActionPerformed
        // TODO add your handling code here:
        PatientAccount.createForm(userEmail);
        this.dispose();
    }//GEN-LAST:event_PatientUpdateBackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void createForm(String _patientId, String _patientEmail) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientUpdate(_patientId, _patientEmail).setVisible(true);
            }
        });
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientUpdate().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PatientUpdateBackButton;
    private javax.swing.JButton PatientUpdateButton;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel contactErrorText;
    private javax.swing.JTextField contactNumberField;
    private javax.swing.JLabel emailErrorText;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel nameErrorText;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel passErrorText;
    private javax.swing.JPasswordField passField;
    // End of variables declaration//GEN-END:variables
}
